Repository libexpat/libexpat, pull requests merged in 2019-09, with the labels that each got.

#318 Deny internal entities closing the doctype (for #317)
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug, security

#335 CMake: Build fuzzing Expat once, not twelve times
  expat/CMakeLists.txt
Labels: compilation, enhancement

#337 qa.sh: Auto-detect QA_COMPILER
  .travis.yml
  expat/qa.sh
Labels: compilation, enhancement

#338 xmlwf: Improve "xmlwf -h" help output
  expat/Changes
  expat/Makefile.am
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
  expat/xmlwf/xmlwf_helpgen.sh
Labels: enhancement

#336 CMake option EXPAT_CHAR_TYPE=(char|ushort|wchar_t) + two other small CMake fixes
  .travis.yml
  appveyor.yml
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/cmake/expat-config.cmake.in
  expat/win32/build_expat_iss.bat
Labels: bug, compilation, enhancement

#341 xmlwf: Fix exit code for case without "-d DIRECTORY"
  expat/Changes
  expat/tests/xmltest.sh
  expat/xmlwf/xmlwf.c
Labels: bug

#343 Autotools: Enable clang tool chain to generate libraries (for #312)
  expat/configure.ac
Labels: compilation

#354 Cover more build flags (fixes #324)
  .travis.yml
  expat/lib/xmlparse.c
  expat/lib/xmlrole.c
  expat/qa.sh
  expat/tests/runtests.c
Labels: enhancement
