Repository libexpat/libexpat, pull requests merged in 2021-04, with the labels that each got.

#456 GitHub Actions: Enable periodic CI runs
  .github/workflows/autotools-cmake.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .travis.sh
  expat/cmake/autotools/expat.cmake
Labels: enhancement

#457 Fix and cover list of exported symbols
  .github/workflows/autotools-cmake.yml
  .github/workflows/data/exported-symbols.txt
  .github/workflows/scripts/list-shared-library-symbols.sh
  expat/CMakeLists.txt
  expat/Changes
  expat/lib/Makefile.am
  expat/lib/internal.h
  expat/lib/libexpat.def
  expat/lib/libexpatw.def
  expat/tests/Makefile.am
Labels: enhancement

#459 CMake: Support absolute paths for CMAKE_INSTALL_(LIB|INCLUDE)DIR (fixes #458)
  expat/CMakeLists.txt
  expat/Changes
Labels: bug, compilation

#465 Fix doc/reference.html badly inserted ul tag (fixes #464)
  expat/doc/reference.html
Labels: enhancement

#463 Small xmlwf refactoring
  expat/xmlwf/xmlwf.c
Labels: enhancement

#467 Resolve macro HAVE_EXPAT_CONFIG_H
  expat/CMakeLists.txt
  expat/configure.ac
  expat/lib/winconfig.h
  expat/lib/xmlparse.c
  expat/lib/xmlrole.c
  expat/lib/xmltok.c
  expat/tests/chardata.c
  expat/tests/runtests.c
  expat/tests/structdata.c
  expat/xmlwf/xmlfile.c
Labels: enhancement

#468 xmlwf: Simplify synopsis
  expat/Changes
  expat/doc/xmlwf.xml
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
  expat/xmlwf/xmlwf_helpgen.sh
Labels: enhancement

#469 xmlwf: Improve manpage
  expat/Changes
  expat/doc/xmlwf.xml
Labels: enhancement

#470 [XML_MIN_SIZE only] Fix segfault with UTF-16 CDATA (fixes #332)
  expat/Changes
  expat/lib/xmltok.c
  expat/lib/xmltok_impl.c
  expat/tests/runtests.c
Labels: bug
