Repository libexpat/libexpat, pull requests merged in 2021-03, with the labels that each got.

#441 fuzzers: Address Clang warning -Wunused-parameter
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
Labels: compilation, enhancement

#446 Quick-port Linux jobs from Travis CI to GitHub Actions
  .github/workflows/linux.yml
  .travis.yml
Labels: enhancement

#447 Windows: Drop support for Visual Studio <=14.0/2015
  appveyor.yml
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
Labels: compilation, enhancement, windows

#444 xmlwf: Resolve exit status 2 ambiguity
  expat/Changes
  expat/doc/xmlwf.xml
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: bug

#450 configure.ac: Apply partial autoupdate-2.71
  expat/Changes
  expat/configure.ac
Labels: compilation, enhancement

#451 Make GNU Autotools install CMake files
  .github/workflows/autotools-cmake.yml
  expat/Changes
  expat/Makefile.am
  expat/cmake/autotools/expat-config-version.cmake.in
  expat/cmake/autotools/expat-noconfig.cmake.in
  expat/cmake/autotools/expat-package-init.cmake
  expat/cmake/autotools/expat.cmake
  expat/configure.ac
Labels: enhancement

#452 configure.ac: Fix use of M4 macro "expat_version"
  .github/workflows/autotools-cmake.yml
  expat/Changes
  expat/configure.ac
Labels: bug, compilation

#453 typo: Buildung -> Building
  expat/README.md
Labels: bug

#455 CMake: Be less rejective towards unsupported MSVC compilers for Conan (#454)
  expat/CMakeLists.txt
Labels: bug, compilation
