Repository libexpat/libexpat, pull requests merged in 2022-07, with the labels that each got.

#610 lib: Address Cppcheck 2.8.1 warning / fix CI
  expat/Changes
  expat/lib/xmlparse.c
Labels: enhancement

#614 fix(docs) update XML_DTD symbol visibility
  expat/doc/reference.html
Labels: bug, documentation

#611 Fix .def files syntax for MinGW
  expat/lib/libexpat.def
  expat/lib/libexpatw.def
Labels: enhancement, compilation, windows

#620 CMake: Improve documentation on variables
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
Labels: enhancement
