Repository libexpat/libexpat, pull requests merged in 2022-01, with the labels that each got.

#536 Actions: Check for realistic minimum CMake version requirement
  .github/workflows/cmake-required-version.yml
  expat/Changes
Labels: enhancement, compilation

#534 [CVE-2021-45960] lib: Detect and prevent troublesome left shifts in function storeAtts (fixes #531)
  expat/Changes
  expat/lib/xmlparse.c
Labels: security

#541 run.sh.in: Do not use Wine with Cygwin and MSYS2
  expat/Changes
  expat/run.sh.in
Labels: bug, windows

#538 [CVE-2021-46143] lib: Prevent integer overflow on m_groupSize in function doProlog (fixes #532)
  expat/Changes
  expat/lib/xmlparse.c
Labels: security

#539 [CVE-2022-22822 to CVE-2022-22827] lib: Prevent more integer overflows
  .github/workflows/linux.yml
  expat/Changes
  expat/lib/xmlparse.c
Labels: security

#543 Prepare release 2.4.3 (part of #533)
  .github/workflows/cmake-required-version.yml
  .github/workflows/linux.yml
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/coverage.sh
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/lib/xmltok_ns.c
  expat/run.sh.in
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: security, releasing

#546 [>=2.3.0] Autotools: Fix broken CMake support under Cygwin
  expat/cmake/autotools/expat-noconfig__windows.cmake.in
  expat/configure.ac
Labels: bug, compilation, windows

#550 [CVE-2022-23852] Prevent XML_GetBuffer signed integer overflow
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug, security

#545 [>=2.3.0] xmlwf: Fix a memory leak on output file opening error (fixes #544)
  expat/Changes
  expat/xmlwf/xmlwf.c
Labels: bug

#551 [CVE-2022-23990] lib: Prevent integer overflow in function doProlog
  expat/Changes
  expat/lib/xmlparse.c
Labels: bug, security

#553 Stop casting void* results from calls to .malloc_fcn
  expat/lib/xmlparse.c
Labels: enhancement, compilation

#554 Prepare release 2.4.4 (part of #552)
  .gitignore
  expat/.gitignore
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/Makefile.am
  expat/doc/reference.html
  expat/doc/valid-xhtml10.png
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
  expat/win32/expat.iss
  expat/xmlwf/xmlwf.c
Labels: security, releasing
