Repository libexpat/libexpat, pull requests merged in 2022-08, with the labels that each got.

#621 CMake: Render .def file from a template to fix linking (fixes #512) + apply .def file with MinGW
  expat/CMakeLists.txt
  expat/Changes
  expat/lib/Makefile.am
  expat/lib/libexpat.def.cmake
  expat/lib/libexpatw.def
  expat/win32/expat.iss
Labels: bug, compilation, windows

#624 CMake: Produce libexpat-1.dll with MinGW in line with GNU Autotools (fixes #622)
  .github/workflows/autotools-cmake.yml
  expat/CMakeLists.txt
  expat/Changes
  expat/coverage.sh
  expat/qa.sh
Labels: enhancement, compilation, windows

#631 File expat/fuzz/.gitignore changed to not ignore already-committed source files (fixes #630)
  expat/fuzz/.gitignore
Labels: enhancement

#633 coverage.sh: Exclude MinGW headers
  expat/coverage.sh
Labels: enhancement

#634 lib: Fix compilation for -D__USE_MINGW_ANSI_STDIO=0
  expat/Changes
  expat/lib/internal.h
Labels: bug, windows

#636 CMake: Drop leading whitespace from a #cmakedefine line in file expat_config.h.cmake to workaround issues with Meson
  expat/apply-clang-format.sh
  expat/expat_config.h.cmake
Labels: enhancement, compilation
