Repository libexpat/libexpat, pull requests merged in 2022-10, with the labels that each got.

#656 [2.4.9] CMake: Fix generation of pkgconfig file
  expat/CMakeLists.txt
Labels: bug

#645 Fix corruption from undefined entities (fixes #612, variation of #615)
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug

#658 [2.4.9] CMake: Fix static library name when building with MinGW
  expat/CMakeLists.txt
Labels: bug

#653 Stop leaking tag bindings (fixes #652)
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug

#654 Fix processing of nested entities (fixes #613)
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug

#663 Protect header expat_config.h from multiple inclusion
  .github/workflows/data/expat_config_h_cmake__expected.txt
  .github/workflows/data/expat_config_h_in__expected.txt
  expat/Changes
  expat/configure.ac
  expat/expat_config.h.cmake
Labels: enhancement

#650 [CVE-2022-43680] Fix overeager DTD destruction (fixes #649)
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug, security

#666 Improve examples
  expat/CMakeLists.txt
  expat/Changes
  expat/examples/elements.c
  expat/examples/outline.c
Labels: enhancement

#668 Prepare release 2.5.0 (part of #667)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/examples/elements.c
  expat/examples/outline.c
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: security, releasing

#669 Fix miscellaneous Clang and Cppcheck 2.9 style warnings
  expat/lib/siphash.h
  expat/lib/xmlparse.c
  expat/lib/xmltok.c
  expat/tests/chardata.c
  expat/tests/memcheck.c
  expat/tests/runtests.c
  expat/tests/structdata.c
  expat/xmlwf/readfilemap.c
  expat/xmlwf/xmlwf.c
Labels: enhancement

#671 Fix getDebugLevel handling of empty environment variable value
  expat/lib/xmlparse.c
Labels: enhancement
