Repository libexpat/libexpat, pull requests merged in 2022-02, with the labels that each got.

#563 Extend .mailmap
  .mailmap
  expat/examples/elements.c
  expat/examples/outline.c
  expat/lib/xmlparse.c
  expat/lib/xmlrole.c
  expat/lib/xmltok.c
  expat/tests/benchmark/benchmark.c
  expat/tests/runtests.c
  expat/xmlwf/xmlfile.c
  expat/xmlwf/xmlwf.c
Labels: enhancement

#558 [CVE-2022-25313] lib: Prevent stack exhaustion in build_model
  expat/lib/xmlparse.c
Labels: bug, security

#559 [CVE-2022-25315] lib: Prevent integer overflow in storeRawNames
  expat/lib/xmlparse.c
Labels: bug, security

#561 [CVE-2022-25236] lib: Protect against insertion of namesep characters into namespace URIs
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug, security

#562 [CVE-2022-25235] lib: Protect against malformed encoding (e.g. malformed UTF-8)
  expat/Changes
  expat/lib/xmltok.c
  expat/lib/xmltok_impl.c
  expat/tests/runtests.c
Labels: bug, security

#564 Prepare release 2.4.5 (part of #557)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/Makefile.am
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/lib/xmltok.c
  expat/lib/xmltok_impl.c
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: security, releasing

#566 Fix build_model regression
  expat/Changes
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug

#568 Prepare release 2.4.6 (part of #567)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: releasing

#571 tests: Resolve use of macros NAN and INFINITY for GNU G++ 4.8.2 (fixes #569)
  expat/Changes
  expat/tests/runtests.c
Labels: bug

#570 CMake/Windows: store Expat version in the dll
  expat/CMakeLists.txt
  expat/Makefile.am
  expat/win32/expat.iss
  expat/win32/version.rc
Labels: enhancement

#574 lib: Make hardcoded namespace URIs easier to find
  expat/lib/xmlparse.c
Labels: enhancement
