Repository libexpat/libexpat, pull requests merged in 2022-04, with the labels that each got.

#598 AppVeyor: Add MSVC 2022
  appveyor.yml
  expat/Changes
Labels: enhancement, windows

#599 CMake: Add missing XML_STATIC to test runners and fuzzers on Windows (related to #597)
  expat/CMakeLists.txt
  expat/Changes
Labels: compilation, windows

#595 [style] Added parentheses around macro arguments
  expat/lib/siphash.h
Labels: enhancement
