Repository libexpat/libexpat, pull requests merged in 2022-03, with the labels that each got.

#575 doc: Document that a call to XML_FreeContentModel can be done at a later time from outside the element declaration handler
  expat/doc/reference.html
  expat/lib/expat.h
Labels: enhancement, documentation

#577 lib: Relax fix to CVE-2022-25236 with regard to RFC 3986 URI characters (fixes #572)
  expat/Changes
  expat/doc/reference.html
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
Labels: bug

#580 Prepare release 2.4.7 (part of #578)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/Makefile.am
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: releasing

#581 Fix windows installer (related to #555, follow-up to #570)
  expat/Changes
  expat/win32/expat.iss
Labels: bug, compilation, windows

#582 CMake: Enforce library versioning compatible with GNU Libtool for macOS (fixes #55)
  expat/CMakeLists.txt
  expat/Changes
Labels: enhancement

#588 Actions: Make robust toward outdated images
  .github/workflows/autotools-cmake.yml
  .github/workflows/valid-xml.yml
Labels: enhancement

#586 Actions: Migrate off moving Git tags
  .github/workflows/autotools-cmake.yml
  .github/workflows/cmake-required-version.yml
  .github/workflows/coverage.yml
  .github/workflows/cppcheck.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/valid-xml.yml
Labels: enhancement

#589 Actions: Upgrade Clang from 13 to 14
  .github/workflows/coverage.yml
  .github/workflows/linux.yml
  .travis.sh
  expat/Changes
Labels: enhancement

#587 Fix pkg-config files
  expat/CMakeLists.txt
  expat/Changes
  expat/expat.pc.cmake
  expat/expat.pc.in
Labels: bug

#591 Prepare release 2.4.8 (part of #590)
  .github/workflows/autotools-cmake.yml
  .github/workflows/coverage.yml
  .github/workflows/cppcheck.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/macos.yml
  .github/workflows/valid-xml.yml
  .travis.sh
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/runtests.c
  expat/win32/expat.iss
Labels: releasing
