Repository libexpat/libexpat, pull requests merged in 2023-11, with the labels that each got.

#785 win32|cmake: Fix FileVersion and ProductVersion in DLL version info
  expat/CMakeLists.txt
  expat/Makefile.am
  expat/win32/.gitignore
  expat/win32/expat.iss
  expat/win32/version.rc.cmake
Labels: bug, compilation, windows

#786 tests: Use NAN and INFINITY of C99 and C++11
  expat/tests/acc_tests.c
Labels: enhancement

#777 Fix issues for compilation with XML_DTD undefined
  .github/workflows/data/expat_config_h_cmake__expected.txt
  .github/workflows/data/expat_config_h_in__expected.txt
  .github/workflows/linux.yml
  expat/CMakeLists.txt
  expat/configure.ac
  expat/coverage.sh
  expat/doc/reference.html
  expat/expat_config.h.cmake
  expat/lib/expat.h
  expat/lib/internal.h
  expat/lib/libexpat.def.cmake
  expat/lib/xmlparse.c
  expat/tests/acc_tests.c
  expat/tests/alloc_tests.c
  expat/tests/basic_tests.c
  expat/tests/common.c
  expat/tests/common.h
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/misc_tests.c
  expat/tests/ns_tests.c
  expat/tests/nsalloc_tests.c
  expat/tests/runtests.c
  expat/xmlwf/xmlwf.c
Labels: bug

#788 tests: Narrow test_buffer_can_grow_to_max mingw allocation workaround at compile time
  expat/tests/basic_tests.c
Labels: enhancement, compilation

#787 tests: Migrate more tests to variable chunk size parsing
  expat/tests/alloc_tests.c
  expat/tests/basic_tests.c
  expat/tests/common.c
  expat/tests/handlers.c
  expat/tests/misc_tests.c
  expat/tests/ns_tests.c
Labels: enhancement

#790 CMake: Build `tests/benchmark/benchmark.c` for `EXPAT_BUILD_TESTS`
  expat/CMakeLists.txt
  expat/tests/benchmark/benchmark.c
Labels: enhancement, compilation
