Repository libexpat/libexpat, pull requests merged in 2023-09, with the labels that each got.

#738 Make branch `pull-674-sandwich` mergable to `master`
  expat/tests/basic_tests.c
  expat/tests/chardata.c
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/minicheck.c
  expat/tests/ns_tests.c
  expat/tests/structdata.c
Labels: enhancement

#739 codespell.yml: Make CI reject spelling errors using codespell + fix two typos
  .github/workflows/codespell.yml
  expat/CMakeLists.txt
  expat/Changes
Labels: bug, enhancement, documentation, ci

#744 xmlwf: Improve language and URL clickability in help output
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: enhancement

#745 Document the importance of isFinal + adjust tests accordingly
  expat/doc/reference.html
  expat/tests/basic_tests.c
  expat/tests/ns_tests.c
Labels: enhancement, documentation

#746 CMake: Sort xmlwf sources alphabetically
  expat/CMakeLists.txt
Labels: enhancement, compilation

#747 tests/handlers.h: Be explicit about direct dependency expat_config.h
  expat/tests/handlers.h
Labels: enhancement, compilation

#748 tests: Restore that all of runtestspp is run through a C++ compiler
  expat/CMakeLists.txt
  expat/expat_config.h.cmake
  expat/tests/.gitignore
  expat/tests/Makefile.am
  expat/tests/acc_tests_cxx.cpp
  expat/tests/alloc_tests_cxx.cpp
  expat/tests/basic_tests_cxx.cpp
  expat/tests/chardata_cxx.cpp
  expat/tests/common_cxx.cpp
  expat/tests/dummy_cxx.cpp
  expat/tests/handlers_cxx.cpp
  expat/tests/memcheck.c
  expat/tests/memcheck_cxx.cpp
  expat/tests/minicheck.c
  expat/tests/minicheck_cxx.cpp
  expat/tests/misc_tests_cxx.cpp
  expat/tests/ns_tests_cxx.cpp
  expat/tests/nsalloc_tests_cxx.cpp
  expat/tests/runtests_cxx.cpp
  expat/tests/structdata.c
  expat/tests/structdata_cxx.cpp
Labels: enhancement, compilation

#751 CMake: Require a C99 compiler
  expat/CMakeLists.txt
Labels: enhancement, compilation

#750 tests: Require a C++11 compiler
  .github/workflows/data/expat_config_h_in__expected.txt
  .github/workflows/scripts/list_exported_macros.sh
  expat/CMakeLists.txt
  expat/acinclude.m4
  expat/configure.ac
  expat/conftools/ax-cxx-compile-stdcxx-11.m4
  expat/conftools/ax-cxx-compile-stdcxx.m4
  expat/coverage.sh
  expat/qa.sh
Labels: enhancement, compilation

#749 CMake: Require CMake >=3.5.0
  expat/CMakeLists.txt
Labels: enhancement, compilation

#753 Fix parse-size-dependent "invalid token" error for external entities that start with a byte order mark
  expat/lib/xmlparse.c
  expat/tests/acc_tests.c
  expat/tests/basic_tests.c
  expat/tests/minicheck.c
  expat/tests/minicheck.h
  expat/tests/misc_tests.c
  expat/tests/ns_tests.c
Labels: bug

#755 Repeat tests with different SINGLE_BYTES chunk sizes
  expat/tests/basic_tests.c
  expat/tests/common.c
  expat/tests/common.h
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/minicheck.c
  expat/tests/minicheck.h
  expat/tests/runtests.c
Labels: enhancement

#757 Add isFinal=XML_TRUE to more tests
  expat/tests/basic_tests.c
Labels: enhancement

#758 Run SINGLE_BYTES with no chunking, too
  expat/tests/alloc_tests.c
  expat/tests/handlers.c
  expat/tests/runtests.c
Labels: enhancement

#759 xmlwf: Support custom buffer size for XML_GetBuffer and read
  expat/xmlwf/xmlfile.c
  expat/xmlwf/xmlfile.h
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: enhancement

#760 doc/reference.html: Upgrade to OK.css 1.2.0
  expat/doc/ok.min.css
  expat/doc/reference.html
Labels: enhancement, documentation

#761 xmlwf: Support --help and --version
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: enhancement
