Repository libexpat/libexpat, pull requests merged in 2023-10, with the labels that each got.

#763 Fix codespell CI + mass-replace "re-use[d]" by "reuse[d]"
  .github/workflows/codespell.yml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/ns_tests.c
Labels: enhancement, documentation, ci

#765 Make inclusion to expat_config.h consistent
  expat/lib/xmlparse.c
  expat/lib/xmlrole.c
  expat/lib/xmltok.c
  expat/tests/chardata.c
  expat/tests/runtests.c
  expat/xmlwf/xmlfile.c
  expat/xmlwf/xmlwf.c
Labels: enhancement, compilation

#762 doc/reference.html: Promote function XML_ParseBuffer more
  expat/doc/reference.html
Labels: enhancement, documentation

#766 lib/xmlparse.c: Improve parse buffer variables documentation
  expat/lib/xmlparse.c
Labels: enhancement, documentation

#764 Be stricter about macro XML_CONTEXT_BYTES at build time
  .github/workflows/linux.yml
  expat/CMakeLists.txt
  expat/configure.ac
  expat/doc/reference.html
  expat/expat_config.h.cmake
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/basic_tests.c
  expat/tests/handlers.c
Labels: enhancement, compilation

#772 tests/memcheck.c: Avoid false positive -Wuse-after-free
  expat/tests/memcheck.c
Labels: enhancement, compilation

#773 Upgrade Clang from 15 to 17
  .ci.sh
  .github/workflows/linux.yml
  expat/lib/xmltok.c
  expat/lib/xmltok_impl.c
  expat/xmlwf/readfilemap.c
Labels: enhancement, compilation, ci

#774 tests: Rename fail_unless to assert_true for clarity
  expat/tests/basic_tests.c
  expat/tests/common.c
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/minicheck.c
  expat/tests/minicheck.h
Labels: enhancement

#779 doc/reference.html: Add HTML anchors to definition of XML_* macros
  expat/doc/reference.html
Labels: enhancement, documentation

#781 tests/acc_tests.c: Move second BOM accounting test to the right place
  expat/tests/acc_tests.c
Labels: enhancement

#780 xmlparse.c: Fix `NULL` pointer dereference in `setContext` via `XML_ExternalEntityParserCreate` for `XML_DTD` undefined
  expat/lib/xmlparse.c
  expat/tests/misc_tests.c
Labels: bug

#783 tests: Stop switching between XML_Parse and _XML_Parse_SINGLE_BYTES
  expat/tests/acc_tests.c
  expat/tests/basic_tests.c
  expat/tests/handlers.c
  expat/tests/handlers.h
Labels: enhancement

#784 tests/handlers.h: Drop unused type XmlParseFunction
  expat/tests/handlers.h
Labels: enhancement

#771 Grow buffer based on current size
  expat/lib/xmlparse.c
  expat/tests/basic_tests.c
Labels: enhancement
