Repository libexpat/libexpat, pull requests merged in 2024-09, with the labels that each got.

#886 Remove `XML_DTD` guards before `is_param` accesses
  expat/lib/xmlparse.c
Labels: enhancement

#890 [CVE-2024-45490] lib: Reject negative len for `XML_ParseBuffer` (fixes #887)
  expat/doc/reference.html
  expat/lib/xmlparse.c
  expat/tests/basic_tests.c
Labels: bug, security

#891 [CVE-2024-45491] lib: Detect integer overflow in `dtdCopy` (fixes #888)
  expat/lib/xmlparse.c
Labels: bug, security

#892 [CVE-2024-45492] lib: Detect integer overflow in function `nextScaffoldPart` (fixes #889)
  expat/lib/xmlparse.c
Labels: bug, security

#896 Prepare release 2.6.3 (part of #894, ETA 2024-09-04)
  .ci.sh
  .github/workflows/autotools-cmake.yml
  .github/workflows/cmake-required-version.yml
  .github/workflows/codespell.yml
  .github/workflows/coverage.yml
  .github/workflows/cppcheck.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/scripts/mass-cppcheck.sh
  .github/workflows/valid-xml.yml
  appveyor.yml
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/Makefile.am
  expat/README.md
  expat/apply-clang-format.sh
  expat/buildconf.sh
  expat/configure.ac
  expat/doc/Makefile.am
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/fix-xmltest-log.sh
  expat/gennmtab/gennmtab.c
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/qa.sh
  expat/tests/Makefile.am
  expat/tests/misc_tests.c
  expat/win32/build_expat_iss.bat
  expat/win32/expat.iss
Labels: security, releasing

#898 `.gitignore`: Add missing example `element_declarations`
  expat/examples/.gitignore
Labels: enhancement

#902 Tests: Reduce use of global parser
  expat/tests/basic_tests.c
  expat/tests/handlers.c
  expat/tests/handlers.h
Labels: enhancement

#904 tests: Resolve duplicate handler `accumulate_char_data`
  expat/tests/common.c
  expat/tests/common.h
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/misc_tests.c
Labels: enhancement
