Repository libexpat/libexpat, pull requests merged in 2024-04, with the labels that each got.

#853 Always provide path to find(1) for portability
  expat/Makefile.am
  expat/README.md
  expat/qa.sh
Labels: bug, compilation

#856 Fix `main()` to `main(void)`
  expat/ConfigureChecks.cmake
  expat/configure.ac
  expat/gennmtab/gennmtab.c
Labels: enhancement, compilation

#855 cmake: Fix check for symbols `size_t` and `off_t` (fixes #854)
  .github/workflows/data/expat_config_h_cmake__expected.txt
  .github/workflows/data/expat_config_h_in__expected.txt
  expat/ConfigureChecks.cmake
  expat/configure.ac
  expat/expat_config.h.cmake
Labels: bug, compilation, cmake

#851 autotools: Sync CMake templates with CMake 3.27
  expat/cmake/autotools/expat.cmake
Labels: enhancement, cmake, autotools

#864 tests: Convert README to Markdown and update.
  expat/tests/Makefile.am
  expat/tests/README.md
  expat/tests/README.txt
  expat/win32/expat.iss
Labels: enhancement, documentation
