Repository libexpat/libexpat, pull requests merged in 2024-01, with the labels that each got.

#797 fuzz: improve coverage
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
Labels: enhancement, fuzzing

#798 Make GitHub Actions enforce clang-tidy clean code + address current clang-tidy warnings
  .github/workflows/clang-tidy.yml
  expat/apply-clang-tidy.sh
  expat/examples/element_declarations.c
  expat/tests/acc_tests.c
  expat/tests/basic_tests.c
Labels: enhancement, ci

#800 clang-tidy: Address warnings `readability-avoid-const-params-in-decls` and `readability-named-parameter`
  expat/apply-clang-tidy.sh
  expat/lib/xmlparse.c
  expat/lib/xmlrole.h
  expat/lib/xmltok.c
  expat/lib/xmltok.h
  expat/tests/handlers.c
  expat/tests/handlers.h
  expat/tests/minicheck.h
Labels: enhancement

#803 Fix Cppcheck CI for Cppcheck 2.13.0
  .github/workflows/cppcheck.yml
  .github/workflows/scripts/mass-cppcheck.sh
Labels: bug, ci

#799 Make CI run fuzzing regression tests (fixes #367)
  .github/workflows/fuzzing.yml
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
Labels: enhancement, ci, fuzzing

#801 fuzz: Improve coverage by maybe stopping the parser
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
Labels: enhancement, fuzzing

#808 CI: Upgrade to clang-tidy 18
  .github/workflows/clang-tidy.yml
  expat/tests/misc_tests.c
Labels: enhancement, ci

#809 CI: Upgrade to clang-format 18
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  expat/apply-clang-format.sh
  expat/lib/xmlparse.c
Labels: enhancement, ci
