Repository libexpat/libexpat, pull requests merged in 2024-03, with the labels that each got.

#837 Add missing #821 #824 to 2.6.1 change log
  expat/Changes
Labels: enhancement, documentation

#841 Reject direct parameter entity recursion (part of #839)
  expat/lib/xmlparse.c
  expat/tests/basic_tests.c
Labels: bug, fuzzing

#842 Prevent billion laughs attacks in isolated external parser (part of #839)
  expat/lib/xmlparse.c
  expat/tests/acc_tests.c
Labels: fuzzing

#847 [2.6.1] Fix DOCBOOK_TO_MAN variable use in doc Makefile
  expat/doc/Makefile.am
Labels: compilation

#843 Prepare release 2.6.2 (part of #838, ETA 2024-03-13)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/misc_tests.c
  expat/win32/expat.iss
Labels: security, releasing

#849 Allow triggering GitHub Actions workflows manually
  .github/workflows/autotools-cmake.yml
  .github/workflows/cmake-required-version.yml
  .github/workflows/codespell.yml
  .github/workflows/coverage.yml
  .github/workflows/cppcheck.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/valid-xml.yml
Labels: enhancement, ci

#741 Drop support for Visual Studio 15 2017
  appveyor.yml
  expat/CMake.README
  expat/CMakeLists.txt
  expat/README.md
  expat/doc/reference.html
  expat/win32/README.txt
  expat/win32/build_expat_iss.bat
Labels: enhancement, compilation, windows
