Repository libexpat/libexpat, pull requests merged in 2024-10, with the labels that each got.

#905 `README.md`: Document use of Expat via CMake >=3.18 with `FetchContent` and `SOURCE_SUBDIR`
  expat/README.md
Labels: enhancement, documentation, cmake

#903 Add alias expat::expat
  expat/CMakeLists.txt
Labels: cmake

#907 CI: Upgrade to Clang 19
  .ci.sh
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/fuzzing.yml
  .github/workflows/linux.yml
Labels: enhancement, ci

#910 Fix CI / `linux.yml`: Fix mishandling of package `debsuryorg-archive-keyring`
  .github/workflows/linux.yml
Labels: ci

#913 `macos.yml`: Drop `macos-12` and add `macos-15`
  .github/workflows/macos.yml
Labels: enhancement, ci

#914 Fix signedness of format strings
  expat/examples/element_declarations.c
  expat/lib/xmlparse.c
  expat/xmlwf/xmlfile.c
Labels: enhancement

#915 [CVE-2024-50602] Stop `XML_ResumeParser` from crashing
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/misc_tests.c
Labels: bug, security
