Repository libexpat/libexpat, pull requests merged in 2024-02, with the labels that each got.

#814 tests: Fix `CLOCKS_PER_SEC` guard for arm64 FreeBSD reality
  expat/tests/basic_tests.c
Labels: enhancement

#813 Protect against closing entities out of order (fixes #812)
  expat/lib/xmlparse.c
  expat/tests/misc_tests.c
Labels: bug, fuzzing

#815 pkg-config: Add missing `-DXML_STATIC` for Windows (alternative to #805)
  expat/expat.pc.cmake
  expat/expat.pc.in
Labels: bug, compilation, windows

#818 Get clang-format CI back in sync
  expat/lib/xmlparse.c
Labels: ci

#819 Fix compiler warnings
  expat/lib/expat.h
  expat/lib/internal.h
Labels: enhancement, compilation

#817 tests: Replace clock counting with counting scanned bytes
  expat/lib/internal.h
  expat/lib/xmlparse.c
  expat/tests/basic_tests.c
Labels: enhancement, ci

#824 Autotools: Re-work handling of xmlwf.1 (fixes #821)
  expat/configure.ac
  expat/doc/Makefile.am
Labels: compilation

#829 Hide test-only code behind new (internal) macro `XML_TESTING` (alternative to #826)
  expat/CMakeLists.txt
  expat/apply-clang-tidy.sh
  expat/lib/Makefile.am
  expat/lib/internal.h
  expat/lib/xmlparse.c
  expat/tests/Makefile.am
Labels: enhancement, compilation

#833 `configure.ac`: Protect against `expat_config.h.in` defining `SIZEOF_VOID_P`
  expat/configure.ac
Labels: enhancement, compilation

#836 Expose billion laughs API with `XML_DTD` without `XML_GE` (fixes #828)
  expat/doc/reference.html
  expat/lib/expat.h
Labels: bug

#834 Prepare release 2.6.1 (part of #832, ETA 2024-02-29)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/Makefile.am
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/Makefile.am
  expat/lib/expat.h
  expat/lib/internal.h
  expat/lib/xmlparse.c
  expat/tests/Makefile.am
  expat/tests/misc_tests.c
  expat/win32/expat.iss
Labels: releasing
