Repository libexpat/libexpat, pull requests merged in 2025-09, with the labels that each got.

#1024 xmlwf: Fix help generator (follow-up to #789)
  expat/xmlwf/xmlwf_helpgen.py
Labels: enhancement

#1027 docs: Add missing `<p>..</p>` wrap
  expat/doc/reference.html
Labels: enhancement, documentation

#1026 xmlwf: Mention supported environment variables in `--help` output
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: enhancement, documentation

#1031 Start calling Cppcheck without `--suppress=objectIndex --suppress=unknownMacro`
  .github/workflows/scripts/mass-cppcheck.sh
  expat/Changes
Labels: enhancement, ci

#1034 [CVE-2025-59375] Start tracking and limiting use of dynamic memory (fixes #1018)
  .github/workflows/data/exported-symbols.txt
  .github/workflows/scripts/mass-cppcheck.sh
  expat/Changes
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/fuzz/xml_lpm_fuzzer.cpp
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
  expat/lib/expat.h
  expat/lib/internal.h
  expat/lib/libexpat.def.cmake
  expat/lib/xmlparse.c
  expat/tests/alloc_tests.c
  expat/tests/basic_tests.c
  expat/tests/nsalloc_tests.c
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: bug, security, fuzzing

#1035 CI: Upgrade to Clang 21
  .ci.sh
  .github/workflows/clang-format.yml
  .github/workflows/clang-static-analyzer.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/coverity-scan.yml
  .github/workflows/fuzzing.yml
  .github/workflows/linux.yml
  expat/Changes
  expat/expat_config.h.cmake
  expat/lib/expat.h
  expat/lib/expat_external.h
  expat/lib/xmlrole.h
  expat/lib/xmltok.h
  expat/tests/minicheck.h
Labels: enhancement, ci

#1037 Drop an OpenVMS support leftover (related to #14)
  expat/Changes
  expat/lib/xmlrole.h
Labels: enhancement

#1038 Prepare release 2.7.2 (part of #1030, ETA 2025-09-16)
  .ci.sh
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy.yml
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/tests/alloc_tests.c
  expat/tests/handlers.c
  expat/tests/misc_tests.c
  expat/tests/nsalloc_tests.c
  expat/win32/build_expat_iss.bat
  expat/win32/expat.iss
  expat/xmlwf/unixfilemap.c
  expat/xmlwf/xmlfile.c
  expat/xmlwf/xmlwf.c
  expat/xmlwf/xmlwf_helpgen.py
Labels: security, releasing

#1032 Normalize `.bat` files to CRLF
  .gitattributes
Labels: enhancement

#1045 `README.md`: Fix typo "R_0_Y_Z" to "R_X_Y_Z"
  expat/README.md
Labels: documentation

#1044 `linux.yml`: Stop aborting at first job failure
  .github/workflows/linux.yml
Labels: enhancement, ci

#1043 Document safe-from-overflow proof (follow-up to #1034)
  expat/Changes
  expat/lib/xmlparse.c
Labels: enhancement, security, documentation

#1041 Improve change log of release 2.7.2
  expat/Changes
Labels: enhancement, documentation

#1047 Make UBSan fatal for regression fuzzing CI
  .github/workflows/fuzzing.yml
  expat/qa.sh
Labels: enhancement, ci, fuzzing

#1049 autotools: Remove `ln -s` discovery
  expat/configure.ac
Labels: enhancement, autotools

#1048 Fix alignment of internal allocations for some non-amd64 architectures (e.g. sparc32) (fixes #1046)
  expat/Changes
  expat/lib/internal.h
  expat/lib/xmlparse.c
  expat/tests/alloc_tests.c
Labels: bug

#1053 `xmlwf`: Resolve use of functions `XML_GetErrorLineNumber` and `XML_GetErrorColumnNumber`
  expat/xmlwf/xmlfile.c
Labels: enhancement

#1059 Fix detection of asynchronous tags in entities
  expat/lib/xmlparse.c
  expat/tests/misc_tests.c
Labels: bug

#1062 lib: Remove cast that truncates a `size_t` to an `unsigned`
  expat/lib/xmlparse.c
Labels: enhancement
