Repository libexpat/libexpat, pull requests merged in 2025-03, with the labels that each got.

#969 Update Open Group link/comment to HTTPS
  expat/xmlwf/readfilemap.c
Labels: enhancement, documentation

#971 Address Cppcheck warnings + fix Cppcheck CI
  .github/workflows/cppcheck.yml
  .github/workflows/scripts/mass-cppcheck.sh
  expat/Changes
  expat/tests/benchmark/benchmark.c
  expat/tests/minicheck.h
  expat/tests/misc_tests.c
Labels: enhancement, ci

#970 Update links in code comments to HTTPS
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
  expat/qa.sh
  expat/tests/xmltest.sh
Labels: enhancement, documentation

#972 `valid-xml.yml`: Stop `xmllint` from loading DTD from the internet to address flaky CI
  .github/workflows/valid-xml.yml
Labels: enhancement, ci

#975 Prepare release 2.7.0 (part of #974, ETA 2024-13-13)
  .github/workflows/autotools-cmake.yml
  .github/workflows/cmake-required-version.yml
  .github/workflows/coverity-scan.yml
  .github/workflows/cppcheck.yml
  .github/workflows/expat_config_h.yml
  .github/workflows/scripts/mass-cppcheck.sh
  .github/workflows/valid-xml.yml
  expat/CMake.README
  expat/CMakeLists.txt
  expat/Changes
  expat/README.md
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/xmlparse.c
  expat/qa.sh
  expat/tests/benchmark/benchmark.c
  expat/tests/minicheck.h
  expat/tests/misc_tests.c
  expat/tests/xmltest.sh
  expat/win32/expat.iss
  expat/xmlwf/readfilemap.c
Labels: security, releasing

#977 Integrate missing fuzzer files with Automake (fixes #976)
  .github/workflows/fuzzing.yml
  expat/Changes
  expat/Makefile.am
Labels: bug, compilation, autotools

#978 `tests/benchmark`: Resolve mistaken double close
  expat/tests/benchmark/benchmark.c
Labels: enhancement

#981 Make GitHub Actions cover compilation with musl
  .github/workflows/musl.yml
  expat/Changes
Labels: enhancement, ci

#984 Fix `printf` format specifiers for 32bit Emscripten (fixes #983) + cover compilation with 32bit Emscripten in CI
  .github/workflows/emscripten.yml
  expat/Changes
  expat/lib/internal.h
Labels: bug, compilation, ci

#986 Address Frama-C warning
  expat/Changes
  expat/lib/xmlparse.c
Labels: enhancement

#987 Make GitHub Actions apply Clang Static Analyzer
  .github/workflows/clang-static-analyzer.yml
  expat/Changes
Labels: enhancement, ci

#991 Re-enable clang-tidy warning `clang-analyzer-valist.Uninitialized`
  expat/Changes
  expat/apply-clang-tidy.sh
Labels: enhancement, ci

#982 Make GitHub Actions run Perl XML::Parser integration tests
  .github/workflows/perl-integration.yml
  expat/Changes
Labels: enhancement, ci

#993 Prepare release 2.7.1 (part of #990, ETA 2025-03-27)
  expat/CMake.README
  expat/CMakeLists.txt
  expat/COPYING
  expat/Changes
  expat/Makefile.am
  expat/README.md
  expat/apply-clang-tidy.sh
  expat/configure.ac
  expat/doc/reference.html
  expat/doc/xmlwf.xml
  expat/lib/expat.h
  expat/lib/internal.h
  expat/lib/xmlparse.c
  expat/tests/common.c
  expat/tests/common.h
  expat/tests/misc_tests.c
  expat/win32/expat.iss
Labels: releasing

#994 `README.md`: Drop AppVeyor badge
  expat/Changes
  expat/README.md
Labels: enhancement, documentation

#999 Address more clang-tidy warnings
  expat/Changes
  expat/apply-clang-tidy.sh
  expat/fuzz/xml_parse_fuzzer.c
  expat/fuzz/xml_parsebuffer_fuzzer.c
  expat/lib/xmlparse.c
  expat/tests/alloc_tests.c
  expat/tests/basic_tests.c
  expat/tests/handlers.c
  expat/tests/misc_tests.c
  expat/tests/nsalloc_tests.c
  expat/xmlwf/unixfilemap.c
  expat/xmlwf/xmlfile.c
  expat/xmlwf/xmlwf.c
Labels: enhancement

#1001 Address clang-tidy warning `misc-no-recursion`
  expat/Changes
  expat/apply-clang-tidy.sh
  expat/lib/xmlparse.c
Labels: enhancement
